Feature branch
sanadwj/Newsweek-clone pull request #1
Opened 2020-08-04 20:37 UTC by pastorp3

2020-08-04 21:36 UTC, expjazz requested changes
## Status: Changes Required :recycle: 
Hey @pastorp3  and @sanadwj 

You did a very good job on this project. The design looks quite good, the code clean, and you displayed a great knowledge of the bootstrap classes.

However, there are still a few aspects that we need to correct in order to advance to the next project:

- [ ] Do not commit unnecessary files (like the node_modules). Please remove them from GitHub for the next review.  I saw that they are on git ignore. Delete them, do a commit, and run npm install again (this should fix the problem).

#### Navbar 

- [x] The subscribe button is overflowing to the next line on the medium screen.

| Yours | Original |
|:---:|:---:|
| ![image](https://user-images.githubusercontent.com/61479648/89344852-f00e9e00-d67c-11ea-9d0f-aa4578317de3.png)|![image](https://user-images.githubusercontent.com/61479648/89344870-fa309c80-d67c-11ea-89a1-6b33066ed833.png)  |

- [x] Newsweek logo is too small on mobile screen size.

| Yours | Original |
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/61479648/89345017-2ba96800-d67d-11ea-9df5-1cba254b311e.png) |![image](https://user-images.githubusercontent.com/61479648/89345092-424fbf00-d67d-11ea-91f9-017accfd83b5.png)  |

#### The debate
- [x] Try to make the styling more like the original. This applies to the whole page, especially the fonts weights and size.

| Yours | Original |
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/61479648/89345282-8642c400-d67d-11ea-8249-af4886c5b43e.png) | ![image](https://user-images.githubusercontent.com/61479648/89345308-8fcc2c00-d67d-11ea-8ec0-6d64987bc884.png) |

- [x] On the mobile size, the size of the image is not proportional.

| Yours | Original |
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/61479648/89346018-c9e9fd80-d67e-11ea-9831-e05eec1f70fc.png) |![image](https://user-images.githubusercontent.com/61479648/89346042-d2423880-d67e-11ea-9184-9c7c040e8352.png)  |


#### More Stories

- [x] The text should wrap around the images.  (All screen sizes)

| Yours | Original |
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/61479648/89345414-bf7b3400-d67d-11ea-8782-dbeaa8e9335b.png) |![image](https://user-images.githubusercontent.com/61479648/89345427-c73ad880-d67d-11ea-96a1-8bec05e702b8.png)  |

- [ ] In the tablet screen, the images are distorted. This happens in different places as well. Address that for the next review.

| Yours | Original |
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/61479648/89345566-0bc67400-d67e-11ea-8728-52f14c650500.png) | ![image](https://user-images.githubusercontent.com/61479648/89345603-1a149000-d67e-11ea-82dd-cc4419e9476f.png) |

- [x] The padding on the medium screen is too much.

| Yours | Original |
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/61479648/89345749-51833c80-d67e-11ea-883c-0da53f1772ea.png) |![image](https://user-images.githubusercontent.com/61479648/89345714-46c8a780-d67e-11ea-90b1-af2dcc50eb86.png) |

- [x] Also in the mobile screen

| Yours | Original |
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/61479648/89345826-74adec00-d67e-11ea-9448-0cd6dfb8a4ea.png) | ![image](https://user-images.githubusercontent.com/61479648/89345881-90b18d80-d67e-11ea-9ab6-33d9e78de4e5.png) |

#### In the magazine

- [x] In the mobile screen, the images need to be centered.

| Yours | Original |
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/61479648/89346231-146b7a00-d67f-11ea-9dd2-af124bb8479a.png) |![image](https://user-images.githubusercontent.com/61479648/89346266-22b99600-d67f-11ea-83fe-91a763ef89fd.png) |

#### Bottom news section

- [x] The layout needs to be closer to the original. Pay extra attention to the fonts and images sizes.

| Yours | Original |
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/61479648/89346530-98bdfd00-d67f-11ea-92c7-67bba093b97d.png) | ![image](https://user-images.githubusercontent.com/61479648/89346550-a07da180-d67f-11ea-9cbd-ed6fc346c1ac.png) |

- [x] Also on tablet and mobile


| Yours | Original |
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/61479648/89346705-e33f7980-d67f-11ea-99c9-e4b9b8ead67a.png) | ![image](https://user-images.githubusercontent.com/61479648/89346739-f0f4ff00-d67f-11ea-8690-0690f445aeda.png) |

#### Subscribe && Newsletter

- [x] Pay attention to the layout in the mobile screen size. (Don't mind the navbar in the screenshot)

| Yours | Original |
|:---:|:---:|
| ![image](https://user-images.githubusercontent.com/61479648/89346889-2f8ab980-d680-11ea-9d68-1fc8fdee9c94.png)|![image](https://user-images.githubusercontent.com/61479648/89346916-3adde500-d680-11ea-84dc-e9462cfb47b4.png) |

#### Footer

- [x] Re-check the layout in all screen sizes again.

| Yours | Original |
|:---:|:---:|
|![image](https://user-images.githubusercontent.com/61479648/89347186-a9bb3e00-d680-11ea-8263-fae6a57c6422.png) | ![image](https://user-images.githubusercontent.com/61479648/89347198-b0e24c00-d680-11ea-8fd7-84d6d4ac8fa7.png) |

#### Even if it seems a lot, it is not. This project is very long and tiresome, and you really did a great job :1st_place_medal: 

### Please make the required changes and resubmit for a new code review once you are ready
Good Luck and Happy Coding :pray:

P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).:smile:

2020-08-05 02:35 UTC, pastorp3 commented
- add all changes

- linters working

2020-08-05 02:59 UTC, voscarmv requested changes
# Nice work so far, team. 👍 

- Good work wrapping the text around the images as the previous TSE requested.

## However, there are some changes required 👀 🧰 🔨 🔧 

- Please update your Mobile view to fix this overflow of the hamburger and subscribe button:
![image](https://user-images.githubusercontent.com/2739245/89366348-5820ac80-d69c-11ea-9d66-7797ac5695a1.png)

- The change requested on "The Debate" section from the previous TSE has not been implemented. Please fix this:
![image](https://user-images.githubusercontent.com/2739245/89366472-8f8f5900-d69c-11ea-925e-2b5fd9c1b221.png)

- Your page overflows to the sides on Tablet view. Please fix this.
![image](https://user-images.githubusercontent.com/2739245/89366631-d8dfa880-d69c-11ea-85e4-443bdcd896cf.png)

- Please center the images on mobile view like the previous TSE requested.
![image](https://user-images.githubusercontent.com/2739245/89366777-278d4280-d69d-11ea-99c5-4c2cf0947ed3.png)

- On width 1024px you have a porblem with overflowing text on the right side articles. Please fix this as well:
![image](https://user-images.githubusercontent.com/2739245/89366860-4be91f00-d69d-11ea-9069-24fb0d0c06ec.png)

- Also, please fix your footer on mobile view:

| Your version | Original |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/2739245/89367025-a97d6b80-d69d-11ea-85c7-ee2630d912da.png) | ![image](https://user-images.githubusercontent.com/2739245/89366994-99fe2280-d69d-11ea-8469-2b851efe7cb7.png) |

### Submit these changes and request a new code review! 😄 👍 

### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

2020-08-05 04:47 UTC, pastorp3 commented
- add changes

2020-08-05 05:50 UTC, tirthajyoti-ghosh requested changes
# Changes required 🛑 

## Impressive progress so far 💪! Thanks for making all the changes 👏.

### However, we need to work on some changes before we can merge.

- The elements in the navbar should be vertically aligned.

  ![image](https://user-images.githubusercontent.com/57726348/89375304-06fbd180-d70b-11ea-9bb2-56ac709998dc.png)

- Please fix this 👇 in the more stories section

  ![image](https://user-images.githubusercontent.com/57726348/89375394-2abf1780-d70b-11ea-8887-dd8ffcb838c8.png)

- The magazine and the text below should have the same width.

  | Source Page| Clone Page |
  |:---:|:---:|
  |![image](https://user-images.githubusercontent.com/57726348/89375590-9b663400-d70b-11ea-8adb-7b7417df3440.png)|![image](https://user-images.githubusercontent.com/57726348/89375538-7f629280-d70b-11ea-92a7-ac4b134a45a4.png)|

- The images here must have the same height and width.

  ![image](https://user-images.githubusercontent.com/57726348/89375794-13ccf500-d70c-11ea-9699-cde885ca542f.png)

  _Possible solution: set image `height` and `width` and give them a `object-fit: cover`_

- The texts are still overflowing, as pointed out by the previous TSE 👇 

  ![image](https://user-images.githubusercontent.com/57726348/89375952-70c8ab00-d70c-11ea-8b95-0571948833d2.png)

- The subscribe and newsletter section is still misaligned 👇 

  | Source Page| Clone Page |
  |:---:|:---:|
  |![image](https://user-images.githubusercontent.com/57726348/89376182-f0ef1080-d70c-11ea-90d0-37d448d3daa9.png)|![image](https://user-images.githubusercontent.com/57726348/89376229-049a7700-d70d-11ea-996c-8a35593c3ef7.png)


- The footer is still misaligned 👇 

  ![image](https://user-images.githubusercontent.com/57726348/89376117-ce5cf780-d70c-11ea-95e7-cbeb95fd78f5.png)

- The navbar should be fixed in tablets and mobile devices.

  | Source Page| Clone Page |
  |:---:|:---:|
  |![image](https://user-images.githubusercontent.com/57726348/89376418-504d2080-d70d-11ea-969e-55bc88b492e5.png)|![image](https://user-images.githubusercontent.com/57726348/89376455-63f88700-d70d-11ea-93b1-01df5812a185.png)|

Your project looks absolutely fantastic. Just make these changes and apply for another code review.

Happy coding 👨‍💻 

*Need help? Shoot me a message on Slack - [@Ghosh](https://app.slack.com/client/T47CT8XPG/DRDM6LAQN/user_profile/URB1MHXK6)*
<hr>

**Tirthajyoti Ghosh**

[GitHub](https://github.com/tirthajyoti-ghosh) | [LinkedIn](https://www.linkedin.com/in/tirthajyoti-ghosh/) | [Twitter](https://twitter.com/terrific_ghosh)

2020-08-05 07:47 UTC, pastorp3 commented
- add review changes

- we try to fix the overflow in text but we cant see it in the live server

- already add width and height and also fit cover to img and still the same

2020-08-05 12:13 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello @sanadwj @pastorp3** 
Good job with your new submission for this project :muscle:  :muscle:
Some improvements are required before you can go ahead:
- [x] Don't overuse important
- [x] Don't repeat yourself, in order to minimize code you can group selectors with the same style definition, or you can try creating new classes.
- [x] remove the horizontal scrollbar
- [x]  Check out the "opinion" section and compare with the original, make sure to match the original structure:

| Yours | Original |
|:---:|:---:|
|![image](https://i.imgur.com/jbGzl5vl.png) | ![image](https://i.imgur.com/WfREyjUl.png) |

- [x] in the bottom of your page, math the appearance of the original "subscribe" section:

| Yours | Original |
|:---:|:---:|
|![image](https://i.imgur.com/zmABDt1l.png) | ![image](https://i.imgur.com/tmxp93Al.png) |

### OPTIONAL

- [x] try to use footer and main tags in your page

Please request another review once you are ready! :+1: 

Happy coding :relaxed:

Oscar Andrés Russi Porras

2020-08-05 12:13 UTC, andresporras3423 commented on styles.css
> +    left: 350px !important;
Don't overuse important

2020-08-05 12:13 UTC, andresporras3423 commented on styles.css
> +}
Group selectors with the same style definition

2020-08-05 12:13 UTC, andresporras3423 commented on styles.css
> +  }
Group selectors with the same style definition

2020-08-05 12:13 UTC, andresporras3423 commented on styles.css
> +  }
Group selectors with the same style definition

2020-08-05 16:38 UTC, kubilaycaglayan requested changes
Hello Team :wave: 
Status: Changes Required :recycle: 

Thank you very much for all your efforts :muscle: , looks like your project becoming better and better. :star: 
:battery:  Great opinion section implementation!

- [x]  Please try, one more time, to delete overused "!important" rules. In styles.css file, we have 50 of them.

- [x]  Grouping selectors is an important skill in CSS, as the previous TSE mentioned, try to group your selectors which has the same rules. I wrote an explanation, please check below.

- [ ]  In the subscribe section, those two magazine pictures should be on the different lines, check the previous TSE's comment to see the original, please. 

:camera_flash:  **Screenshot**

![subscribe section](https://user-images.githubusercontent.com/60448833/89438985-341fa280-d752-11ea-8701-5ae7ea5d0f93.png)

That's it...
With all my respect...

2020-08-05 16:38 UTC, kubilaycaglayan commented on styles.css
> +}
Group selectors with the same style definition(same as the previous TSE requested)
You can easily do this by:
``` 
.dis-none {
  display: none;
}
```

And you can use **dis-none** class name in any element you want.

Moreover, you have a built-in Bootstrap class name for this, d-none

Check this life-changing [link](https://getbootstrap.com/docs/4.5/utilities/display/#hiding-elements)

2020-08-05 18:34 UTC, pastorp3 commented
- add review changes

2020-08-05 18:45 UTC, expjazz approved these changes
## Status: Project Approved :clap: 

The page looks really great, and you did a great job on everything that was requested above. The page looks much better than when I first reviewed :1st_place_medal: 

Good Luck and Happy Coding :pray:

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Expedito Andrade).:smile:_

2020-08-05 19:03 UTC, merged